services:
  app:
    image: alvinwidi33/seasaloon-backend:latest
    container_name: backend-app
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env

  postgres:
    image: postgres:17
    container_name: seasaloon
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: